name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Ou a branch que você deseja usar

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'  # Ou a versão que você está usando

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Ajuste se seu comando de build for diferente

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # O diretório onde os arquivos construídos são gerados
